### ISSUE TITLE
Adding same discourse URL twice opens two tabs

### ISSUE THREAD

**Issue by djfarrelly** [alepolidori/chrome-discourse-notifications#1]
If you add the URL during setup, then add it again during via the options page, clicking the discourse icon will open 2 tabs. It seems it doesn't clear out the original event handler. The [code here should do that](https://github.com/alepolidori/chrome-discourse/blob/master/js/background.js#L90-L91), but I'm not sure what's failing.

Thanks for building this extension, just what I needed!

**Comment by alepolidori** [comment]
Thank you for the tip @djfarrelly.
I am happy that it is useful :)
