### ISSUE TITLE
Validate URL

### ISSUE THREAD

**Issue by ww4** [alepolidori/chrome-discourse-notifications#11]
Currently it doesn't validate the URL for your forum or add http.

**Repro:** type in "meta.discourse.org" as your URL. It asks you to log in, but url is bad, so directs to broken page.

Should at least say "invalid URL". Better would be adding http prefix, only if needed.

**Comment by ww4** [comment]
Seems that ANY text string is accepted and no validation is done. I think this counts as a bug?

![gibberish](https://cloud.githubusercontent.com/assets/11318280/10517383/7ce01cde-732a-11e5-94a2-938886312237.png)

**Comment by alepolidori** [comment]
Of course, I've not yet implemented a validation, so it could be considered as a bug :+1:
