### ISSUE TITLE
Improved forum titles

### ISSUE THREAD

**Issue by ww4** [alepolidori/chrome-discourse-notifications#13]
Extension should pull the site name from the root URL. Instead of displaying the raw url ie https://meta.discourse.org, display the root page title "Discourse Meta".

Also, the favicon image should be pulled from the browser's cache. This way it updates correctly if the favicon changes.

**Comment by gsanchietti** [comment]
+1!

**Comment by alepolidori** [comment]
The favicons are get at browser start.
If something goes wrong it uses google s2 service.
First step, is to obtain a more defined icons.
The cache sould be already present, isn't it ?
If the favicon changes a browser restart should be sufficient and that is not frequent task, I think.

@kymetro9999 have you tested that favicon is not pulled from browser cache ?
Have you tested that extension icon don't update after a favicon site changed ?
