### ISSUE TITLE
favicons broken when using relative links

### ISSUE THREAD

**Issue by ww4** [alepolidori/chrome-discourse-notifications#18]
Discourse forums set the URL to their favicon in the settings panel, using either an absolute link or a relative link.

The absolute link works fine, for example https://meta.discourse.org has 

"https://discourse-meta.s3-us-west-amazonaws.com/original/3X/c/b/cb4bec8901221d4a646e45e1fa03db3a65e17f59.png"

Other sites may use relative links, and these show as broken images. http://forum.driveonwood.com has

"/uploads/default/25/5b9df8575801a87e.ico"

This shows only a "broken image" icon. The relative link does not lead back to the original domain.

All relative URLs should be rewritten as absolute URLs, to prevent this issue.

**Comment by alepolidori** [comment]
Thanks for reporting this issue :+1:
