### ISSUE TITLE
Always shows 1 unread notification

### ISSUE THREAD

**Issue by ww4** [alepolidori/chrome-discourse-notifications#19]
Extension always has "1" on the logo, as if there were one unread notification. Opening, closing the popup doesn't clear it. Visiting Discourse and clearing notifications doesn't clear it.

On reinstall the plugin shows zero again. But soon the problem returns. 

In the linked image, all notifications are cleared, yet the logo shows 1 unread.

Running Chrome stable 48.0.2564.116

![](https://gyazo.com/51086d50b5f909088177fcf74264228c.png)

**Comment by alepolidori** [comment]
Hi @ww4, sorry for the late..
You still have the problem with 1.1.4 ver ?

**Comment by ww4** [comment]
Hi @alepolidori I'm sorry but I no longer use the extension, since the official Discourse notification app came out.

**Comment by alepolidori** [comment]
:+1: @ww4 no problem.
What Discourse app do you mean ? That for android or the web app site ?
Thx for the answer

**Comment by ww4** [comment]
I use the Android app now. It works quite well.

**Comment by alepolidori** [comment]
ok thanks.
So I consider closed this issue, because it seems no longer present after the latest update.
Have a nice day ! :-)
