### ISSUE TITLE
Unread Count does not change

### ISSUE THREAD

**Issue by randy-johnson** [alepolidori/chrome-discourse-notifications#25]
I installed this plugin today to use with http://forum.nativescript.org/

It changed the count to 2 unread posts but has not updated since then.

When I click it , the list view does show me new posts but the count never changes.

Let me know if you need additional info.

Thank You,
Randy

**Comment by alepolidori** [comment]
Ok, thank you @randy-johnson for reporting, ASAP I will try to resolve the problem.

**Comment by randy-johnson** [comment]
Any progress on this?

**Comment by alepolidori** [comment]
Sorry @randy-johnson , but I did not have time.
It would be helpful, if there is a method (test site) to reproduce the problem easily, do you know it ?

**Comment by randy-johnson** [comment]
http://forum.nativescript.org/ is the url I use with the addon.

Here is the settings page of the addon: https://goo.gl/gWfstH
Thank you.  

Randy

**Comment by alepolidori** [comment]
@randy-johnson I've published new 1.1.4 version now and it will be available in few hours, I hope. It depends on chrome web store.
When it becomes available, could you please test if the bug has been resolved ?
Otherwise I will reopen the bug...

Thank you

**Comment by randy-johnson** [comment]
My apologies for the late reply.  I missed the git hub notification.  Yes this is fixed.  Thank you very much for fixing it.

Randy

**Comment by alepolidori** [comment]
No problem @randy-johnson and thank you to you for the reporting ! :)
