### ISSUE TITLE
Use new Discourse API

### ISSUE THREAD

**Issue by alepolidori** [alepolidori/chrome-discourse-notifications#27]
https://blog.discourse.org/2017/03/discourse-api-documentation-released/

**Comment by ijcd** [comment]
The issue seems to be a 404 while fetching the current.json?_=XXXXXXXXXXXX file.

```
GENERAL
Request URL:https://elixirforum.com/session/current.json?_=XXXXXXXXXXXXXXX
Request Method:GET
Status Code:404 Not Found
Remote Address:176.9.20.99:443
Referrer Policy:no-referrer-when-downgrade
```

**Comment by ijcd** [comment]
The URL works if pasted directly into the browser. It seems that some sandboxing feature is getting in the way?

**Comment by ijcd** [comment]
https://meta.discourse.org/t/issue-with-api-endpoint-session-current/20757/10
