### ISSUE TITLE
Cannot read property 'map' of undefined (current version on current Chrome)

### ISSUE THREAD

**Issue by ghost** [alepolidori/chrome-discourse-notifications#8]
Empty white popup with this error in JS:

```
popup.js:70 Uncaught (in promise) TypeError: Cannot read property 'map' of undefined
    at chrome-extension://okmkhbdimfnmdhpclfbamachjcpcgcmi/js/popup.js:70:36
```

**Comment by alepolidori** [comment]
Have you logged in into the configured discourse site ?

**Comment by ghost** [comment]
I was already logged in when I was configuring the extension.
I just logged out, configured it again, logged in, but I still see a blank square.

**Comment by alepolidori** [comment]
I am not able to replicate it, but I think that it is caused by a failure getting notifications.
So, the error could be better managed, also better managing the logged out case.
Does it always happen ?

**Comment by alepolidori** [comment]
I've tried to solve it handling the user logged out case, when the "getNotifications" returns no "data.notifications" and "data.notifications.map" throw TypeError.
