### ISSUE TITLE
About Notification

### ISSUE THREAD

**Issue by huyxdotcom01** [alepolidori/chrome-discourse-notifications#9]
We need notification with custom sounds, a mini-box in the right-bottom of the screen (for content post preview)

**Comment by alepolidori** [comment]
Nice :+1:, but it is already implemented by discourse site (as you can see [here](https://meta.discourse.org/t/show-desktop-notifications-when-available/10183/59)).

It could cause some complaints, becuase when you have opened discourse site and new notification happens, you will see 2 desktop notifications popup.

I think it could be useful when no discourse site tab is opened. In this case you don't receive any notifications from the site and the extension can show it, but only in this case.

What do you think about it ?

**Comment by huyxdotcom01** [comment]
It's neccessary. At least one notification must be showed when no discourse
tab is opened. Because our site is not opened in all time.

---

_Thanks and Best Regards!_

## _Nguyễn Minh Huy_

Mobile: +(84) 935 059109
Blog: http://minhhuy150894.github.io
https://minhhuy150894.wordpress.com

**Comment by alepolidori** [comment]
I think it could be useful an option to enable/disable them (a simple checkbox).
Do you think it is better to enable by default or not ?

**Comment by huyxdotcom01** [comment]
I think it's better when it automatically work. Option for sound
notification On/Off switcher.
Why don't we reply to the post without opening in new tab? How do you think
about this?

---

_Thanks and Best Regards!_

## _Nguyễn Minh Huy_

Mobile: +(84) 935 059109
Blog: http://minhhuy150894.github.io
https://minhhuy150894.wordpress.com

**Comment by alepolidori** [comment]
> I think it's better when it automatically work. Option for sound
> notification On/Off switcher.
> Why don't we reply to the post without opening in new tab? How do you think
> about this?

I agree, it could be useful.

**Comment by alepolidori** [comment]
Desktop notifications are displayed when no discourse site is opened.
It is possible to disable them by the option.
Now is not possible to answer to a post using the notification popup and no sound is present.

Thanks to @minhhuy150894 for the idea !
